name: Deploy DEV API

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
  push:
    branches:
      - next
      - main
    paths:
      - 'package.json'
      - 'yarn.lock'
      - 'apps/api/**'
      - 'libs/dal/**'
      - 'libs/shared/**'
env:
  REGISTRY_IMAGE: ghcr.io/ras-devops/novu/api

jobs:
  get_version:
    uses: ./.github/workflows/get-version.yml
    permissions:
      contents: read
      pull-requests: read
    with:
      environment: Development
      environment_short: prod
    secrets: inherit

  test_api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

  deploy_dev_api:
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [get_version, test_api]
    timeout-minutes: 80
    environment: Development
    permissions:
      contents: write
      packages: write
      deployments: write
      id-token: write
    strategy:
      matrix:
#        name: ['novu/api-ee', 'novu/api']
        name: ['novu/api']
        platform:
          - linux/amd64
          - linux/arm64
    steps:
      - uses: actions/checkout@v3
#        with:
#          submodules: ${{ contains (matrix.name,'-ee') }}
#          token: ${{ secrets.SUBMODULES_TOKEN }}

      - name: Echo image to output
        id: Echo-image
        env:
          IMAGE_TAG: ${{ needs.get_version.outputs.env_tag }}
          SHA_SHORT: ${{ needs.get_version.outputs.sha_short }}
          SHA: ${{ needs.get_version.outputs.sha }}
        run: |
          echo "IMAGE_TAG = $IMAGE_TAG"
          echo "SHA_SHORT = $SHA_SHORT"
          echo "SHA = $SHA"
          echo "RELEASE_VERSION=${{ github.ref_name }}"
          echo "$RELEASE_VERSION"

      - uses: ./.github/actions/setup-project
#        with:
#          submodules: ${{ contains (matrix.name,'-ee') }}

############################################################
#      - name: Version.
#        uses: paulhatch/semantic-version@v5.3.0
#        id: semantic-api
#        with:
#          tag_prefix: "v"
#          version_format: "${major}.${minor}.${patch}"
#          major_pattern: "(MAJOR-API)"
#          major_regexp_flags: "feat(.*)"
#          minor_pattern: "(MINOR-API)"
#          minor_regexp_flags: "perf(.*)"
#          debug: true
#          bump_each_commit: true
#          bump_each_commit_patch_pattern: "(PATH-API)"
#          change_path: 'apps/api/** package.json yarn.lock libs/dal/** libs/shared/**'
##          namespace: api
#
#      - name: Set TAGS
#        id: sha_and_tag
#        run: |
#          echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
#          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
#          echo "git_tag=v${{ steps.semantic-api.outputs.version }}" >> $GITHUB_OUTPUT
#          echo "git_version_tag=${{ steps.semantic-api.outputs.version_tag }}" >> $GITHUB_OUTPUT
###############################################################

      - uses: ./.github/actions/docker/build-api
        id: docker_build
        with:
          tag: ${{ needs.get_version.outputs.env_tag }}
          push: 'true'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: ${{ matrix.name }}
          bullmq_secret: ${{ secrets.BULL_MQ_PRO_NPM_TOKEN }}

  push_digest:
    needs: [deploy_dev_api, get_version]
    uses: ./.github/workflows/push-digest.yml
    permissions:
      packages: write
    with:
      environment: Development
      environment_short: dev
      custom_tag: ${{ needs.get_version.outputs.sha }}
      REGISTRY_IMAGE: ghcr.io/ras-devops/novu/api
