name: Get version for applications

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  workflow_call:
    inputs:
      # The environment with the GH secrets environment.
      environment:
        required: true
        type: string
      environment_short:
        required: true
        type: string
    outputs:
      env_tag:
        description: 'The current version of the application with suffix'
        value: ${{ jobs.get_version.outputs.tag }}
      sha:
        description: 'The current sha of the code'
        value: ${{ jobs.get_version.outputs.sha }}
      sha_short:
        description: 'The current sha short of the code'
        value: ${{ jobs.get_version.outputs.sha_short }}
      version:
        description: 'The current version of the application without suffix'
        value: ${{ jobs.get_version.outputs.version }}


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  get_version:
    runs-on: ubuntu-latest
    timeout-minutes: 80
    environment: ${{ inputs.environment }}
    outputs:
      tag: ${{ steps.sha_and_tag.outputs.tag }}
      sha: ${{ steps.sha_and_tag.outputs.sha }}
      sha_short: ${{ steps.sha_and_tag.outputs.sha_short }}
      version: ${{ steps.sha_and_tag.outputs.version }}
    permissions:
      contents: write
      packages: write
      deployments: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get version
        uses: paulhatch/semantic-version@v5.3.0
        id: semantic
        with:
          tag_prefix: "v"
          version_format: "${major}.${minor}.${patch}-${increment}"
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          debug: true
          bump_each_commit: true
          bump_each_commit_patch_pattern: "(PATH)"

      - name: Get previous tag
        id: previoustag
        uses: 'WyriHaximus/github-action-get-previous-tag@v1'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get next minor version
        id: semver
        uses: 'WyriHaximus/github-action-next-semvers@v1'
        with:
          version: ${{ steps.previoustag.outputs.tag }}

      - name: Create release
        id: create_release_id
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.semver.outputs.patch }}
          release_name: Release ${{ steps.semver.outputs.patch }}

      - name: 'Set TAGS. Version: ${{ steps.semantic.outputs.version_tag }}'
        id: sha_and_tag
        run: |
          echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "version=${{ steps.semantic.outputs.version }}" >> $GITHUB_OUTPUT
          echo "previous_version=${{ steps.semantic.outputs.previous_version }}" >> $GITHUB_OUTPUT
          if [[ "${{ steps.semantic.outputs.version }}" == *-0 ]]; then
            echo "tag=${{ steps.semver.outputs.patch }}" >> $GITHUB_OUTPUT
          else
            echo "tag=${{ steps.semver.outputs.patch }}-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          fi
#          if [[ "${{ steps.semantic.outputs.version }}" == *-0 ]]; then
#            echo "tag=${{ steps.semantic.outputs.version_tag }}" >> $GITHUB_OUTPUT
#          else
#            echo "tag=${{ steps.semantic.outputs.version_tag }}-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
#          fi
