name: Get version for applications

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  workflow_call:
    inputs:
      # The environment with the GH secrets environment.
      environment:
        required: true
        type: string
      environment_short:
        required: true
        type: string
    outputs:
      env_tag:
        description: 'The current version of the application with suffix'
        value: ${{ jobs.get_version.outputs.tag }}
      sha:
        description: 'The current sha of the code'
        value: ${{ jobs.get_version.outputs.sha }}
      sha_short:
        description: 'The current sha short of the code'
        value: ${{ jobs.get_version.outputs.sha_short }}
      version:
        description: 'The current version of the application without suffix'
        value: ${{ jobs.get_version.outputs.version }}


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  get_version:
    runs-on: ubuntu-latest
    timeout-minutes: 80
    environment: ${{ inputs.environment }}
    outputs:
      tag: ${{ steps.sha_and_tag.outputs.tag }}
      sha: ${{ steps.sha_and_tag.outputs.sha }}
      sha_short: ${{ steps.sha_and_tag.outputs.sha_short }}
      version: ${{ steps.sha_and_tag.outputs.version }}
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/github-script@v7
        id: get_pr_data
        with:
          script: |
            return (
              await github.rest.repos.listPullRequestsAssociatedWithCommit({
                commit_sha: context.sha,
                owner: context.repo.owner,
                repo: context.repo.repo,
              })
            ).data[0];

      - name: Pull Request data
        id: show-pr-data
        run: |
          echo "${{ fromJson(steps.get_pr_data.outputs.result).number }}"
          echo "${{ fromJson(steps.get_pr_data.outputs.result).title }}"
          echo "pr_number=${{ fromJson(steps.get_pr_data.outputs.result).number }}" >> $GITHUB_OUTPUT
          echo "pr_title=${{ fromJson(steps.get_pr_data.outputs.result).title }}" >> $GITHUB_OUTPUT

      - name: Get latest git tag
        id: get-latest-tag
        run: |
          echo "latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1))" >> $GITHUB_OUTPUT

      - name: Get LABELS
        id: get-labels
        env:
          PR_NUMBER: ${{ steps.show-pr-data.outputs.pr_number }}
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "cli_tag=$(git tag -l | tail -1)"
          echo $cli_tag
          echo ${{ env.PR_NUMBER }}
          gh api -H "Accept: application/vnd.github+json" /repos/ras-devops/novu/issues/${{ env.PR_NUMBER }}/labels | jq '[.[].name]' > /tmp/label_list
          cat /tmp/label_list

      - name: Determine Version Bump
        id: determine-bump
        if: ${{ steps.check-existing-tag.outputs.bump != 'none' }}
        run: |
          labels=$(cat /tmp/label_list)
          current_version="${{ steps.get-latest-tag.outputs.latest_tag }}"

          # Determine the bump type (major, minor, patch, or build)
          if [[ $labels == *"bump:major"* ]]; then
            bump_type="major"
          elif [[ $labels == *"bump:minor"* ]]; then
            bump_type="minor"
          elif [[ $labels == *"bump:patch"* ]]; then
            bump_type="patch"
          else
            echo "No version bump labels found. Bumping build number."
            bump_type="build"
          fi

          # Determine prerelease type and build number
          prerelease_label=$(echo $labels | grep -Eo 'pre:(alpha|beta|stable)' | head -1)
          build_number=$(echo $current_version | grep -Eo 'build:[0-9]+' | grep -Eo '[0-9]+' | tail -1)

          # If prerelease labels are present, bump the build number
          if [ -n "$prerelease_label" ]; then
            build_number=$((build_number + 1))
          fi

          # If there are prerelease labels, include them in the new version
          if [ -n "$prerelease_label" ]; then
            new_version="${current_version%-*}-$prerelease_label.$build_number"
          else
            new_version="${current_version%-*}.$build_number"
          fi

          echo "Bumping $bump_type Version"
          echo "Previous Version: $current_version"
          echo "New Version: $new_version"
          echo "bump_type=$bump_type" >> $GITHUB_ENV
          echo "new_version=$new_version" >> $GITHUB_ENV

#      - name: Get LABELS
#        id: get-labels
#        env:
#          PR_NUMBER: ${{ steps.pr.outputs.pull_request_number }}
#          GH_TOKEN: ${{ github.token }}
#        run: |
#          echo "cli_tag=$(git tag -l | tail -1)"
#          echo $cli_tag
#          echo ${{ env.PR_NUMBER }}
#          gh api -H "Accept: application/vnd.github+json" /repos/ras-devops/novu/issues/${{ env.PR_NUMBER }}/labels | jq '[.[].name]' > /tmp/label_list
#          cat /tmp/label_list

#      - name: Dump GitHub context
#        env:
#          GITHUB_CONTEXT: ${{ toJson(github) }}
#        run: echo "$GITHUB_CONTEXT"
#
#      - uses: jefflinse/pr-semver-bump@v1.6.0
#        name: Bump and Tag Version
#        id: semantic
#        with:
#          mode: bump
#          repo-token: ${{ secrets.GITHUB_TOKEN }}
#          require-release-notes: false
#          release-notes-prefix: ''
#          release-notes-suffix: ''
#          with-v: true
#          base-branch: false
#
#      - name: Get Tag via CLI
#        id: get-tag-via-cli
#        run: |
#          echo "cli_tag=$(git tag -l | tail -1)"
#          echo $cli_tag
#          env
#      - name: Bump version
#        uses: haya14busa/action-bumpr@v1
#        if: "!startsWith(github.ref, 'refs/tags/')"
#        id: semantic
#      - name: Get version
#        uses: paulhatch/semantic-version@v5.3.0
#        id: semantic
#        with:
#          tag_prefix: "v"
#          version_format: "${major}.${minor}.${patch}-${increment}"
#          major_pattern: "(MAJOR)"
#          minor_pattern: "(MINOR)"
#          debug: true
#          bump_each_commit: true
#          bump_each_commit_patch_pattern: "(PATH)"

#      - name: Set TAGS
#        id: sha_and_tag
#        run: |
#          echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
#          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
#          echo "version=${{ steps.semantic.outputs.version }}" >> $GITHUB_OUTPUT
#          echo "current_version=${{ steps.semantic.outputs.old-version }}" >> $GITHUB_OUTPUT
#          if [[ -z "${{ steps.semantic.outputs.version }}" ]]; then
#            echo "tag=$(git tag -l | tail -1)-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
#          else
#            echo "tag=${{ steps.semantic.outputs.version }}" >> $GITHUB_OUTPUT
#          fi

#          if [[ "${{ steps.semantic.outputs.version }}" == *-0 ]]; then
#
#            echo "tag=${{ steps.semantic.outputs.version_tag }}" >> $GITHUB_OUTPUT
#          else
#            echo "tag=${{ steps.semantic.outputs.version_tag }}-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
#          fi

#      - name: VARS
#        id: test
#        run: |
#          echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
#          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
#          echo "version=${{ steps.sha_and_tag.outputs.tag }}"
#          echo "old-version=${{ steps.sha_and_tag.outputs.current_version }}"
