name: "Manifests merging"

on:
  workflow_dispatch:
    inputs:
      docker_name:
        description: 'Name for docker image'
        required: false
      custom_tag:
        description: 'Image TAG'
        required: false
      github_token:
        description: 'The token to use for logging into ghcr.io'
        required: false
      REGISTRY_IMAGE:
        description: 'REGISTRY_IMAGE'
        required: false

jobs:
  merge_digest:
    runs-on: ubuntu-latest
    timeout-minutes: 80
    permissions:
      packages: write
      deployments: write
      id-token: write
    steps:
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: /tmp/digests
          pattern: digests-*
          merge-multiple: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        env:
          IMAGE_TAG: ${{ inputs.custom_tag }}
          REGISTRY_IMAGE: ${{ inputs.REGISTRY_IMAGE }}
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          tags: ${{ env.IMAGE_TAG }}
      - name: Login To Registry
        shell: bash
        env:
          GH_ACTOR: ${{ github.actor }}
          GH_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo $GH_PASSWORD | docker login ghcr.io -u $GH_ACTOR --password-stdin
      - name: Echo DOCKER_METADATA_OUTPUT_JSON
        shell: bash
        run: |
          echo $DOCKER_METADATA_OUTPUT_JSON
      - name: Create manifest list and push
        working-directory: /tmp/digests
        env:
          IMAGE_TAG: ${{ inputs.custom_tag }}
          REGISTRY_IMAGE: ${{ inputs.REGISTRY_IMAGE }}  # Corrected line
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env.REGISTRY_IMAGE }}@sha256:%s ' *)
      - name: Inspect image
        env:
          IMAGE_TAG: ${{ inputs.custom_tag }}
          REGISTRY_IMAGE: ${{ inputs.REGISTRY_IMAGE }
        run: |
          docker buildx imagetools inspect ${{ env.REGISTRY_IMAGE }}:${{ env.IMAGE_TAG }}
