# .github/workflows/release.yml
name: Release

on:
  pull_request:
    types: [closed]
    branches:
      - next
      - main

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'

    - name: Bump version
      uses: haya14busa/action-bumpr@v1
      id: semantic
