# .github/workflows/release.yml
name: Release

on:
  pull_request:
    types: [closed]
    branches:
      - next
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    if: github.event.pull_request.merged

    steps:
      - name: Tag
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: next
          release_strategy: tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
