name: Build, tag and push docker image to ghcr.io

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  workflow_call:
    inputs:
      # The environment with the GH secrets environment.
      environment:
        required: true
        type: string
      # The name of the package under which the docker image will be published on GH Packages.
      package_name:
        required: true
        type: string
      # The path to the project in the monorepo.
      project_path:
        required: true
        type: string
      # The port used for testing. This is not a required input, and it defaults to '1341'.
      # This value is added, so you can test the image after it's built in test mode and by doing a health-check.
      test_port:
        required: false
        default: '1341'
        type: string
      # The boolean that helps to determine whether to perform a health check. This is not a required input and defaults to false.
      health_check:
        required: false
        default: false
        type: boolean
      # The tag under which the image is built, it should align with the name in the project command docker:build
      local_tag:
        required: true
        type: string
      # The environment tag. Possible values are dev, stg, and prod. This is not a required input of type string.
      env_tag:
        required: false
        type: string
      github_token:
        description: 'The token to use for logging into ghcr.io'
        required: true
        type: string
    outputs:
      docker_image:
        description: 'The image that was built'
        value: ${{ jobs.reusable_docker.outputs.docker_image }}
      docker_image_ee:
        description: 'The enterprise image that was built'
        value: ${{ jobs.reusable_docker.outputs.docker_image_ee }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  reusable_docker:
    runs-on: ubuntu-latest
    timeout-minutes: 80
    environment: ${{ inputs.environment }}
    outputs:
      docker_image: ${{ steps.save-image-to-output.outputs.IMAGE }}
      docker_image_ee: ${{ steps.save-image-to-output.outputs.IMAGE_EE }}
    permissions:
      contents: read
      packages: write
      deployments: write
      id-token: write
    strategy:
      matrix:
        name: [ '${{ inputs.package_name }}-gg', '${{ inputs.package_name }}' ]
        platform:
          - linux/amd64
          - linux/arm64
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup-project

      - name: Prepare
        shell: bash
        run: |
          platform=${{ matrix.platform }}
          service=${{ matrix.name }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV
          echo "SERVICE_NAME=$(basename "${service//-/-}")" >> $GITHUB_ENV

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: 'image=moby/buildkit:v0.13.1'

      - name: Login To Registry
        shell: bash
        env:
          GH_ACTOR: ${{ github.actor }}
          GH_PASSWORD: ${{ inputs.github_token }}
        run: |
          echo $GH_PASSWORD | docker login ghcr.io -u $GH_ACTOR --password-stdin

      - name: Build, tag, and push image to ghcr.io
        id: build-image
        if: ${{ inputs.env_tag == 'dev' || inputs.env_tag == 'stg' }}
        env:
          REGISTRY_OWNER: ras-devops
          DOCKER_NAME: ${{ matrix.name }}
          LOCAL_TAG: ${{ inputs.local_tag }}
          IMAGE_TAG: ${{ github.sha }}
          ENV_TAG: ${{ inputs.env_tag }}
          PROJECT_PATH: ${{ inputs.project_path }}
          GH_ACTOR: ${{ github.actor }}
          GH_PASSWORD: ${{ secrets.GH_PACKAGES }}
          DOCKER_BUILD_ARGUMENTS: "--cache-from type=registry,ref=ghcr.io/ras-devops/novu/cache:build-cache-${{ env.SERVICE_NAME }}-${{ env.PLATFORM_PAIR }} --cache-to type=registry,ref=ghcr.io/ras-devops/novu/cache:build-cache-${{ env.SERVICE_NAME }}-${{ env.PLATFORM_PAIR }},mode=max --metadata-file metadata.json --iidfile image-id.txt --platform=${{ matrix.platform }} --output=type=image,name=ghcr.io/ras-devops/${{ inputs.docker_name }},push-by-digest=true,name-canonical=true"
        run: |
          cd $PROJECT_PATH && npm run docker:build
          docker tag $LOCAL_TAG ghcr.io/$REGISTRY_OWNER/$DOCKER_NAME:$IMAGE_TAG
          docker tag $LOCAL_TAG ghcr.io/$REGISTRY_OWNER/$DOCKER_NAME:$ENV_TAG
          docker push ghcr.io/$REGISTRY_OWNER/$DOCKER_NAME:$IMAGE_TAG
          docker push ghcr.io/$REGISTRY_OWNER/$DOCKER_NAME:$ENV_TAG

      - name: Production build, tag, and push image to ghcr.io
        id: build-prod-image
        if: ${{ inputs.env_tag == 'prod' }}
        env:
          REGISTRY_OWNER: ras-devops
          DOCKER_NAME: ${{ matrix.name }}
          LOCAL_TAG: ${{ inputs.local_tag }}
          IMAGE_TAG: ${{ github.sha }}
          ENV_TAG: ${{ inputs.env_tag }}
          PROJECT_PATH: ${{ inputs.project_path }}
          GH_ACTOR: ${{ github.actor }}
          GH_PASSWORD: ${{ secrets.GH_PACKAGES }}
        run: |
          echo $GH_PASSWORD | docker login ghcr.io -u $GH_ACTOR --password-stdin
          cd $PROJECT_PATH && npm run docker:build
          docker tag $LOCAL_TAG ghcr.io/$REGISTRY_OWNER/$DOCKER_NAME:$IMAGE_TAG
          docker tag $LOCAL_TAG ghcr.io/$REGISTRY_OWNER/$DOCKER_NAME:$ENV_TAG
          docker tag $LOCAL_TAG ghcr.io/$REGISTRY_OWNER/$DOCKER_NAME:latest
          docker push ghcr.io/$REGISTRY_OWNER/$DOCKER_NAME:$IMAGE_TAG
          docker push ghcr.io/$REGISTRY_OWNER/$DOCKER_NAME:$ENV_TAG
          docker push ghcr.io/$REGISTRY_OWNER/$DOCKER_NAME:latest

      - name: Save image to output
        id: save-image-to-output
        env:
          REGISTRY_OWNER: ras-devops
          DOCKER_NAME: ${{ matrix.name }}
          IMAGE_TAG: ${{ github.sha }}
          OUTPUT_NAME: ${{ contains(matrix.name,'-gg') && 'IMAGE_EE' || 'IMAGE' }}
        run: |
          echo "$OUTPUT_NAME=ghcr.io/$REGISTRY_OWNER/$DOCKER_NAME:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        env:
          REGISTRY_OWNER: ras-devops
          DOCKER_NAME: ${{ matrix.name }}
          IMAGE_TAG: ${{ github.sha }}
          REGISTRY_IMAGE: ghcr.io/ras-devops/${{ inputs.docker_name }}:${{ github.sha }}
        with:
          images: ghcr.io/$REGISTRY_OWNER/$DOCKER_NAME
          tags: ${{ env.IMAGE_TAG }}

      - name: Export digest
        shell: bash
        env:
          GH_ACTOR: ${{ github.actor }}
          GH_PASSWORD: ${{ inputs.github_token }}
          IMAGE_TAG: ${{ github.sha }}
          REGISTRY_OWNER: ras-devops
          DOCKER_NAME: ${{ inputs.docker_name }}
          PROJECT_PATH: ${{ inputs.project_path }}
        run: |
          echo $GH_PASSWORD | docker login ghcr.io -u $GH_ACTOR --password-stdin
          mkdir -p /tmp/digests
          cd $PROJECT_PATH
          image_id=$(cat image-id.txt)
          digest=$(docker inspect --format='{{index .RepoDigests 0}}' "$image_id")
          touch "/tmp/digests/$(echo "$digest" | awk -F'@sha256:' '{print $2}')"
          ls -la /tmp/digests/
          echo "----------------- CAT METADATA JSON  ---------------------"
          cat ./metadata.json
          echo "----------------- CAT IMAGE ID ---------------------"
          cat image-id.txt
          echo "----------------- NEW Dicgest ------------------"
          echo $digest

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.SERVICE_NAME }}-digests-${{ env.PLATFORM_PAIR }}
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1

  push_digest:
    needs: [reusable_docker]
    uses: ./.github/workflows/push-digest.yml
    permissions:
      packages: write
    strategy:
      matrix:
        name: [ '${{ inputs.package_name }}-gg', '${{ inputs.package_name }}' ]
    with:
      environment:  ${{ inputs.environment }}
      service_name: ${{ matrix.name }}
      custom_tag: ${{ github.sha }}
      REGISTRY_IMAGE: ghcr.io/ras-devops/${{ matrix.name }}

#      - name: Health check test
#        id: health-check
#        if: ${{ inputs.health_check == 'true' && (steps.build-image.outcome == 'success' || steps.build-prod-image.outcome == 'success') }}
#        env:
#          REGISTRY_OWNER: ras-devops
#          DOCKER_NAME: ${{ matrix.name }}
#          LOCAL_TAG: ${{ inputs.local_tag }}
#          IMAGE_TAG: ${{ github.sha }}
#          TEST_PORT: ${{ inputs.test_port }}
#          GH_ACTOR: ${{ github.actor }}
#          GH_PASSWORD: ${{ secrets.GH_PACKAGES }}
#        run: |
#          echo $GH_PASSWORD | docker login ghcr.io -u $GH_ACTOR --password-stdin
#
#          docker run --network=host --name $LOCAL_TAG -dit --env NODE_ENV=test ghcr.io/$REGISTRY_OWNER/$DOCKER_NAME:$IMAGE_TAG
#          docker run --network=host appropriate/curl --retry 10 --retry-delay 5 --retry-connrefused http://127.0.0.1:$TEST_PORT/v1/health-check | grep 'ok'
